name: cashew
description: budgeting your monthly nut

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  auto_size_text: ^3.0.0
  package_info_plus: ^1.4.2
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  url_launcher: ^6.0.20
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^2.3.1
  fl_chart: ^0.50.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
